# 데이터 불러오기

In [577]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import gc
from glob import glob

In [578]:
glob = sorted(glob("csv_file_folder/*"))[::-1] # 가장 최신 데이터가 위에 올 수 있게 설정

In [579]:
df = pd.read_csv(glob[0]) # 가장 최신 데이터(2024_03)만 불러오기
print(df.shape)
df.head(3)

(200, 18)

,NO,MOVIE_NM,DRCTR_NM,MAKR_NM,INCME_CMPNY_NM,DISTB_CMPNY_NM,OPN_DE,MOVIE_TY_NM,MOVIE_STLE_NM,NLTY_NM,TOT_SCRN_CO,SALES_PRICE,VIEWNG_NMPR_CO,SEOUL_SALES_PRICE,SEOUL_VIEWNG_NMPR_CO,GENRE_NM,GRAD_NM,MOVIE_SDIV_NM
0,1.0,파묘,장재현,"(주)쇼박스,(주)엠씨엠씨",NaN,(주)쇼박스,20240222.0,개봉영화,장편,한국,2355.0,7.071885e+10,7260067.0,1.631510e+10,1634201.0,미스터리,15세이상관람가,일반영화
1,2.0,듄: 파트2,드니 빌뇌브,NaN,워너브러더스 코리아(주),워너브러더스 코리아(주),20240228.0,개봉영화,장편,미국,1544.0,1.914196e+10,1617500.0,7.694492e+09,594961.0,액션,12세이상관람가,일반영화
2,3.0,댓글부대,안국진,"(주)영화적순간,주식회사 디믹스스튜디오",NaN,(주)에이스메이커무비웍스,20240327.0,개봉영화,장편,한국,1228.0,5.042399e+09,541058.0,1.309676e+09,134016.0,범죄,15세이상관람가,일반영화

In [580]:
for folder in glob[1:]: # 2024_03을 제외한 나머지 데이터 불러오기
    data = pd.read_csv(folder)
    df = pd.concat([df, data], ignore_index=True) # df에 모든 csv파일 합치기
df.shape

(10872, 18)

In [581]:
display(df.head(3))
df.tail(3)

,NO,MOVIE_NM,DRCTR_NM,MAKR_NM,INCME_CMPNY_NM,DISTB_CMPNY_NM,OPN_DE,MOVIE_TY_NM,MOVIE_STLE_NM,NLTY_NM,TOT_SCRN_CO,SALES_PRICE,VIEWNG_NMPR_CO,SEOUL_SALES_PRICE,SEOUL_VIEWNG_NMPR_CO,GENRE_NM,GRAD_NM,MOVIE_SDIV_NM
0,1.0,파묘,장재현,"(주)쇼박스,(주)엠씨엠씨",NaN,(주)쇼박스,20240222.0,개봉영화,장편,한국,2355.0,7.071885e+10,7260067.0,1.631510e+10,1634201.0,미스터리,15세이상관람가,일반영화
1,2.0,듄: 파트2,드니 빌뇌브,NaN,워너브러더스 코리아(주),워너브러더스 코리아(주),20240228.0,개봉영화,장편,미국,1544.0,1.914196e+10,1617500.0,7.694492e+09,594961.0,액션,12세이상관람가,일반영화
2,3.0,댓글부대,안국진,"(주)영화적순간,주식회사 디믹스스튜디오",NaN,(주)에이스메이커무비웍스,20240327.0,개봉영화,장편,한국,1228.0,5.042399e+09,541058.0,1.309676e+09,134016.0,범죄,15세이상관람가,일반영화

,NO,MOVIE_NM,DRCTR_NM,MAKR_NM,INCME_CMPNY_NM,DISTB_CMPNY_NM,OPN_DE,MOVIE_TY_NM,MOVIE_STLE_NM,NLTY_NM,TOT_SCRN_CO,SALES_PRICE,VIEWNG_NMPR_CO,SEOUL_SALES_PRICE,SEOUL_VIEWNG_NMPR_CO,GENRE_NM,GRAD_NM,MOVIE_SDIV_NM
10869,1983.0,F컵 거유의 육덕녀 무삭제판,버드맨 텟페이,NaN,NaN,(주)영진크리에이티브,20201116,개봉영화,장편,일본,1.0,6000.0,1.0,0.0,0.0,멜로/로맨스,청소년관람불가,일반영화
10870,1984.0,G컵 베이글의 격렬한 플레이,NaN,NaN,(주)빅콘미디어,(주)빅콘미디어,20200328,개봉영화,장편,일본,1.0,6000.0,1.0,0.0,0.0,성인물(에로),청소년관람불가,일반영화
10871,1985.0,G컵 베이글의 능숙한 몸놀림,아라시야마 미치루,NaN,(주)빅콘미디어,(주)빅콘미디어,20200925,개봉영화,장편,일본,1.0,6000.0,1.0,0.0,0.0,성인물(에로),청소년관람불가,일반영화

# 데이터 탐색

## 피쳐명 변경

- No: 번호
- MOVIE_NM: 영화명
- DRCTR_NM: 감독명
- MAKR_NM: 제작사명
- INCME_CMPNY_NM: 수입회사명
- DISTB_CMPNY_NM: 유통회사명
- OPN_DE: 개방일자
- MOVIE_TY_NM: 영화유형명
- MOVIE_STLE_NM: 영화형태명
- NLTY_NM: 국적명
- TOT_SCRN_CO: 총 스크린수
- SALES_PRICE: 매출금액
- VIEWNG_NMPR_CO: 관람인원 수
- SEOUL_SALES_PRICE: 서울매출금액
- SEOUL_VIEWNG_NMPR_CO: 서울관람인원 수
- GENRE_NM: 장르명
- GRAD_NM: 등급명
- MOVIE_SDIV_NM: 영화구분명

In [582]:
df = df.rename(columns={"NO":"번호", "MOVIE_NM":"영화제목", "DRCTR_NM":"감독", "MAKR_NM":"제작사", "INCME_CMPNY_NM":"수입사", "DISTB_CMPNY_NM":"유통사",
                   "OPN_DE":"개봉날짜", "MOVIE_TY_NM":"영화유형", "MOVIE_STLE_NM":"영화형태", "NLTY_NM":"국적", "TOT_SCRN_CO":"총스크린수",
                   "SALES_PRICE":"매출금액", "VIEWNG_NMPR_CO":"관람객", "SEOUL_SALES_PRICE":"서울매출금액", "SEOUL_VIEWNG_NMPR_CO":"서울관람객수",
                   "GENRE_NM":"장르", "GRAD_NM":"등급", "MOVIE_SDIV_NM":"영화구분"})
df.head(3) # 번호 피처 삭제예정

,번호,영화제목,감독,제작사,수입사,유통사,개봉날짜,영화유형,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분
0,1.0,파묘,장재현,"(주)쇼박스,(주)엠씨엠씨",NaN,(주)쇼박스,20240222.0,개봉영화,장편,한국,2355.0,7.071885e+10,7260067.0,1.631510e+10,1634201.0,미스터리,15세이상관람가,일반영화
1,2.0,듄: 파트2,드니 빌뇌브,NaN,워너브러더스 코리아(주),워너브러더스 코리아(주),20240228.0,개봉영화,장편,미국,1544.0,1.914196e+10,1617500.0,7.694492e+09,594961.0,액션,12세이상관람가,일반영화
2,3.0,댓글부대,안국진,"(주)영화적순간,주식회사 디믹스스튜디오",NaN,(주)에이스메이커무비웍스,20240327.0,개봉영화,장편,한국,1228.0,5.042399e+09,541058.0,1.309676e+09,134016.0,범죄,15세이상관람가,일반영화

## 요약본

In [583]:
def resumtable(data):
    summary = pd.DataFrame(data.dtypes).reset_index().rename(columns={"index":"피처", 0:"dtypes"})
    summary["결측치 갯수"] = data.isnull().sum().values
    summary["고윳값 갯수"] = data.nunique().values
    summary["첫번째 값"] = data.iloc[0].values
    summary["두번째 값"] = data.iloc[1].values
    summary["세번째 값"] = data.iloc[2].values
    
    return summary

In [584]:
resumtable(df) # 영화제목 고윳값으로 보면 중복된 데이터 있음 추측

,피처,dtypes,결측치 갯수,고윳값 갯수,첫번째 값,두번째 값,세번째 값
0,번호,float64,595,1985,1.0,2.0,3.0
1,영화제목,object,595,7050,파묘,듄: 파트2,댓글부대
2,감독,object,2109,2454,장재현,드니 빌뇌브,안국진
3,제작사,object,6549,767,"(주)쇼박스,(주)엠씨엠씨",NaN,"(주)영화적순간,주식회사 디믹스스튜디오"
4,수입사,object,7067,222,NaN,워너브러더스 코리아(주),NaN
5,유통사,object,596,542,(주)쇼박스,워너브러더스 코리아(주),(주)에이스메이커무비웍스
6,개봉날짜,object,597,845,20240222.0,20240228.0,20240327.0
7,영화유형,object,595,1,개봉영화,개봉영화,개봉영화
8,영화형태,object,595,4,장편,장편,장편
9,국적,object,595,56,한국,미국,한국
10,총스크린수,float64,1000,611,2355.0,1544.0,1228.0
11,매출금액,float64,7090,1896,70718847542.0,19141960349.0,5042399113.0
12,관람객,float64,2453,1834,7260067.0,1617500.0,541058.0
13,서울매출금액,float64,4243,1716,16315095444.0,7694492061.0,1309676360.0
14,서울관람객수,float64,2092,1608,1634201.0,594961.0,134016.0
15,장르,object,630,21,미스터리,액션,범죄
16,등급,object,595,7,15세이상관람가,12세이상관람가,15세이상관람가
17,영화구분,object,595,2,일반영화,일반영화,일반영화

# 전처리 
- 시각화 하기전 기본 전처리 필요

## 피처 삭제

In [585]:
df

,번호,영화제목,감독,제작사,수입사,유통사,개봉날짜,영화유형,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분
0,1.0,파묘,장재현,"(주)쇼박스,(주)엠씨엠씨",NaN,(주)쇼박스,20240222.0,개봉영화,장편,한국,2355.0,7.071885e+10,7260067.0,1.631510e+10,1634201.0,미스터리,15세이상관람가,일반영화
1,2.0,듄: 파트2,드니 빌뇌브,NaN,워너브러더스 코리아(주),워너브러더스 코리아(주),20240228.0,개봉영화,장편,미국,1544.0,1.914196e+10,1617500.0,7.694492e+09,594961.0,액션,12세이상관람가,일반영화
2,3.0,댓글부대,안국진,"(주)영화적순간,주식회사 디믹스스튜디오",NaN,(주)에이스메이커무비웍스,20240327.0,개봉영화,장편,한국,1228.0,5.042399e+09,541058.0,1.309676e+09,134016.0,범죄,15세이상관람가,일반영화
3,4.0,웡카,폴 킹,NaN,워너브러더스 코리아(주),워너브러더스 코리아(주),20240131.0,개봉영화,장편,미국,1753.0,3.838069e+09,401512.0,9.176151e+08,93348.0,판타지,전체관람가,일반영화
4,5.0,고질라 X 콩: 뉴 엠파이어,아담 윈가드,NaN,워너브러더스 코리아(주),워너브러더스 코리아(주),20240327.0,개봉영화,장편,미국,996.0,3.220813e+09,320982.0,7.506203e+08,69172.0,액션,12세이상관람가,일반영화
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10867,1981.0,D컵여자친구,이정석,스마일컨텐츠,NaN,스마일컨텐츠,20201113,개봉영화,장편,한국,1.0,5.000000e+03,1.0,0.000000e+00,0.0,멜로/로맨스,청소년관람불가,일반영화
10868,1982.0,F컵 거유의 육덕녀,버드맨 텟페이,NaN,(주)영진크리에이티브,(주)영진크리에이티브,20200807,개봉영화,장편,일본,1.0,6.000000e+03,1.0,0.000000e+00,0.0,멜로/로맨스,청소년관람불가,일반영화
10869,1983.0,F컵 거유의 육덕녀 무삭제판,버드맨 텟페이,NaN,NaN,(주)영진크리에이티브,20201116,개봉영화,장편,일본,1.0,6.000000e+03,1.0,0.000000e+00,0.0,멜로/로맨스,청소년관람불가,일반영화
10870,1984.0,G컵 베이글의 격렬한 플레이,NaN,NaN,(주)빅콘미디어,(주)빅콘미디어,20200328,개봉영화,장편,일본,1.0,6.000000e+03,1.0,0.000000e+00,0.0,성인물(에로),청소년관람불가,일반영화
10871,1985.0,G컵 베이글의 능숙한 몸놀림,아라시야마 미치루,NaN,(주)빅콘미디어,(주)빅콘미디어,20200925,개봉영화,장편,일본,1.0,6.000000e+03,1.0,0.000000e+00,0.0,성인물(에로),청소년관람불가,일반영화

### "번호" 피처 삭제

In [586]:
df = df.drop(columns="번호")
df.head(3)

,영화제목,감독,제작사,수입사,유통사,개봉날짜,영화유형,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분
0,파묘,장재현,"(주)쇼박스,(주)엠씨엠씨",NaN,(주)쇼박스,20240222.0,개봉영화,장편,한국,2355.0,7.071885e+10,7260067.0,1.631510e+10,1634201.0,미스터리,15세이상관람가,일반영화
1,듄: 파트2,드니 빌뇌브,NaN,워너브러더스 코리아(주),워너브러더스 코리아(주),20240228.0,개봉영화,장편,미국,1544.0,1.914196e+10,1617500.0,7.694492e+09,594961.0,액션,12세이상관람가,일반영화
2,댓글부대,안국진,"(주)영화적순간,주식회사 디믹스스튜디오",NaN,(주)에이스메이커무비웍스,20240327.0,개봉영화,장편,한국,1228.0,5.042399e+09,541058.0,1.309676e+09,134016.0,범죄,15세이상관람가,일반영화

### "영화유형" 피처 삭제

In [587]:
# 영화유형은 고윳값이 1 이므로 삭제
df = df.drop(columns="영화유형")

## 인덱스 삭제

### 모든값이 결측치인 인덱스 삭제

In [588]:
display(pd.read_csv(glob[0]).tail(3))
display(pd.read_csv(glob[1]).tail(3))
display(pd.read_csv(glob[2]).tail(3))

,NO,MOVIE_NM,DRCTR_NM,MAKR_NM,INCME_CMPNY_NM,DISTB_CMPNY_NM,OPN_DE,MOVIE_TY_NM,MOVIE_STLE_NM,NLTY_NM,TOT_SCRN_CO,SALES_PRICE,VIEWNG_NMPR_CO,SEOUL_SALES_PRICE,SEOUL_VIEWNG_NMPR_CO,GENRE_NM,GRAD_NM,MOVIE_SDIV_NM
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,NO,MOVIE_NM,DRCTR_NM,MAKR_NM,INCME_CMPNY_NM,DISTB_CMPNY_NM,OPN_DE,MOVIE_TY_NM,MOVIE_STLE_NM,NLTY_NM,TOT_SCRN_CO,SALES_PRICE,VIEWNG_NMPR_CO,SEOUL_SALES_PRICE,SEOUL_VIEWNG_NMPR_CO,GENRE_NM,GRAD_NM,MOVIE_SDIV_NM
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,NO,MOVIE_NM,DRCTR_NM,MAKR_NM,INCME_CMPNY_NM,DISTB_CMPNY_NM,OPN_DE,MOVIE_TY_NM,MOVIE_STLE_NM,NLTY_NM,TOT_SCRN_CO,SALES_PRICE,VIEWNG_NMPR_CO,SEOUL_SALES_PRICE,SEOUL_VIEWNG_NMPR_CO,GENRE_NM,GRAD_NM,MOVIE_SDIV_NM
197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [589]:
df = df.dropna(axis="index", how="all") # 모든 값이 결측치인 인덱스 삭제
df.shape

(10277, 16)

In [590]:
df2 = df.copy()

## 영화제목 중복 정리

In [591]:
mask = df["영화제목"].value_counts()>1 # 중복되는 영화 확인
duplicated_movie = df["영화제목"].value_counts()[mask].index # 중복되는 영화제목 추출
cols = ["매출금액", "관람객", "서울매출금액", "서울관람객수"] # 중복영화에서 합해야할 피쳐
len(duplicated_movie)

1729

In [592]:
df.loc[df["영화제목"] == "코다"]

,영화제목,감독,제작사,수입사,유통사,개봉날짜,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분
2799,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),20210831.0,장편,프랑스,308.0,NaN,47.0,NaN,35.0,드라마,12세이상관람가,독립/예술영화
2984,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),20210831.0,장편,프랑스,308.0,NaN,47.0,NaN,36.0,드라마,12세이상관람가,독립/예술영화
3169,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),20210831.0,장편,프랑스,308.0,NaN,681.0,NaN,653.0,드라마,12세이상관람가,독립/예술영화
3405,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,884.0,NaN,246.0,드라마,12세이상관람가,독립/예술영화
3655,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,635.0,NaN,1.0,드라마,12세이상관람가,독립/예술영화
3854,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,903.0,NaN,37.0,드라마,12세이상관람가,독립/예술영화
4080,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,265.0,NaN,51.0,드라마,12세이상관람가,독립/예술영화
4358,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,53.0,NaN,47.0,드라마,12세이상관람가,독립/예술영화
4590,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,946.0,NaN,134.0,드라마,12세이상관람가,독립/예술영화
4857,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,939.0,NaN,419.0,드라마,12세이상관람가,독립/예술영화
5076,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,NaN,NaN,NaN,드라마,12세이상관람가,독립/예술영화
5352,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,NaN,NaN,674.0,드라마,12세이상관람가,독립/예술영화
5585,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,NaN,NaN,558.0,드라마,12세이상관람가,독립/예술영화
5848,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,61.0,NaN,58.0,드라마,12세이상관람가,독립/예술영화
6065,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,516.0,NaN,474.0,드라마,12세이상관람가,독립/예술영화
6305,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,748.0,NaN,450.0,드라마,12세이상관람가,독립/예술영화
6516,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,NaN,NaN,NaN,드라마,12세이상관람가,독립/예술영화
6726,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,NaN,NaN,NaN,드라마,12세이상관람가,독립/예술영화
6954,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,NaN,NaN,NaN,드라마,12세이상관람가,독립/예술영화
7168,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,293.0,NaN,NaN,NaN,NaN,드라마,12세이상관람가,독립/예술영화

In [593]:
for movie in duplicated_movie: # 중복된 영화 [매출금액, 관람객, 서울매출금액, 서울관람객수] 합치기
    for col in cols:
        if df.loc[df["영화제목"] == movie, col].isna().all():
            value = None # 결측치만 있는 피쳐는 그대로 결측치 유지
        else:
            value = df.loc[df["영화제목"] == movie, col].sum(skipna=True) # 결측치 아닌 것들만 더하기
        
        df.loc[df["영화제목"] == movie, col] = value # 결과 업데이트
        
df.loc[df["영화제목"] == "코다"]

,영화제목,감독,제작사,수입사,유통사,개봉날짜,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분
2799,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),20210831.0,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
2984,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),20210831.0,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
3169,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),20210831.0,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
3405,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
3655,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
3854,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
4080,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
4358,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
4590,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
4857,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
5076,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
5352,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
5585,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
5848,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
6065,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
6305,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
6516,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
6726,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
6954,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,308.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화
7168,코다,션 헤이더,NaN,판씨네마(주),판씨네마(주),2021-08-,장편,프랑스,293.0,NaN,6725.0,NaN,3873.0,드라마,12세이상관람가,독립/예술영화

In [594]:
df = df.drop_duplicates(["영화제목", "영화형태", "국적", "등급", "영화구분"]) # 중복된 데이터 제거
print(df.shape)
df.head(3) # 영화제목 고윳값 7050인걸 봤을때 같은 이름의 영화 존재 예상

(7081, 16)

,영화제목,감독,제작사,수입사,유통사,개봉날짜,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분
0,파묘,장재현,"(주)쇼박스,(주)엠씨엠씨",NaN,(주)쇼박스,20240222.0,장편,한국,2355.0,1.057937e+11,10957317.0,2.481515e+10,2507635.0,미스터리,15세이상관람가,일반영화
1,듄: 파트2,드니 빌뇌브,NaN,워너브러더스 코리아(주),워너브러더스 코리아(주),20240228.0,장편,미국,1544.0,2.194099e+10,1886010.0,8.730581e+09,687149.0,액션,12세이상관람가,일반영화
2,댓글부대,안국진,"(주)영화적순간,주식회사 디믹스스튜디오",NaN,(주)에이스메이커무비웍스,20240327.0,장편,한국,1228.0,5.042399e+09,541058.0,1.309676e+09,134016.0,범죄,15세이상관람가,일반영화

In [595]:
del mask, duplicated_movie, value
gc.collect();

In [596]:
mask = df["영화제목"].value_counts()>1
duplicated_movie = df["영화제목"].value_counts()[mask].index # 같은 이름의 영화들
len(duplicated_movie) # 같은 이름의 영화 총 31 편

31

In [597]:
duplicated_movie

Index(['카르멘', '벨파스트', '피델리오', '젠틀맨', '세 여자', '씰벤져스 : 용감한 바다특공대', '말이야 바른 말이지',
       '보지만 말고 넣어', '극장판 콩순이: 장난감나라 대모험', '별의 목소리 X 초속5센티미터', '컴 애즈 유 아',
       '리골레토', '블레이즈', '오픈 더 도어', '남은 인생 10년', '노매드랜드', '리코리쉬 피자', '상견니',
       '센코롤 커넥트', '킹 오브 뉴욕', '레드 로켓', '어웨이크', '앵커', '크레센도', '퍼스트 러브', '헌트',
       '언더그라운드', '마인드 유니버스', '앰뷸런스', '조제, 호랑이 그리고 물고기들', '아르키메데스의 대전'],
      dtype='object', name='영화제목')

In [598]:
# 같은 이름 영화일때 오류가 생김
display(df.loc[df["영화제목"] == "카르멘"])
df2.loc[df2["영화제목"] == "카르멘"]

,영화제목,감독,제작사,수입사,유통사,개봉날짜,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분
7968,카르멘,엠마 단테,NaN,일미디어,일미디어,20210403,장편,이탈리아,10.0,12793200.0,487.0,8612650.0,291.0,공연,15세이상관람가,일반영화
9753,카르멘,NaN,NaN,에스디시코리아 주식회사,에스디시코리아 주식회사,20200603,장편,영국,6.0,12793200.0,487.0,8612650.0,291.0,공연,12세이상관람가,일반영화

,영화제목,감독,제작사,수입사,유통사,개봉날짜,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분
7968,카르멘,엠마 단테,NaN,일미디어,일미디어,20210403,장편,이탈리아,10.0,11973200.0,450.0,8130650.0,271.0,공연,15세이상관람가,일반영화
9753,카르멘,NaN,NaN,에스디시코리아 주식회사,에스디시코리아 주식회사,20200603,장편,영국,6.0,820000.0,37.0,482000.0,20.0,공연,12세이상관람가,일반영화

```
위에 있는 반복문 코드를 놀리고 나면 바로 윗 코드 같은 오류가 생기므로
아래 반복문을 통해 다시 원상태로 바꾸어 준다.
```

In [599]:
for movie in duplicated_movie:
    df.loc[df["영화제목"] == movie, cols] = df2.loc[df2["영화제목"] == movie, cols] # 이름만 같고 다른 영화 원상태 복구
    
display(df.loc[df["영화제목"] == "카르멘"])
df2.loc[df2["영화제목"] == "카르멘"]

,영화제목,감독,제작사,수입사,유통사,개봉날짜,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분
7968,카르멘,엠마 단테,NaN,일미디어,일미디어,20210403,장편,이탈리아,10.0,11973200.0,450.0,8130650.0,271.0,공연,15세이상관람가,일반영화
9753,카르멘,NaN,NaN,에스디시코리아 주식회사,에스디시코리아 주식회사,20200603,장편,영국,6.0,820000.0,37.0,482000.0,20.0,공연,12세이상관람가,일반영화

,영화제목,감독,제작사,수입사,유통사,개봉날짜,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분
7968,카르멘,엠마 단테,NaN,일미디어,일미디어,20210403,장편,이탈리아,10.0,11973200.0,450.0,8130650.0,271.0,공연,15세이상관람가,일반영화
9753,카르멘,NaN,NaN,에스디시코리아 주식회사,에스디시코리아 주식회사,20200603,장편,영국,6.0,820000.0,37.0,482000.0,20.0,공연,12세이상관람가,일반영화

In [600]:
duplicated_movie

Index(['카르멘', '벨파스트', '피델리오', '젠틀맨', '세 여자', '씰벤져스 : 용감한 바다특공대', '말이야 바른 말이지',
       '보지만 말고 넣어', '극장판 콩순이: 장난감나라 대모험', '별의 목소리 X 초속5센티미터', '컴 애즈 유 아',
       '리골레토', '블레이즈', '오픈 더 도어', '남은 인생 10년', '노매드랜드', '리코리쉬 피자', '상견니',
       '센코롤 커넥트', '킹 오브 뉴욕', '레드 로켓', '어웨이크', '앵커', '크레센도', '퍼스트 러브', '헌트',
       '언더그라운드', '마인드 유니버스', '앰뷸런스', '조제, 호랑이 그리고 물고기들', '아르키메데스의 대전'],
      dtype='object', name='영화제목')

In [601]:
display(df.loc[df["영화제목"] == "크레센도"])
df2.loc[df2["영화제목"] == "크레센도"]

,영화제목,감독,제작사,수입사,유통사,개봉날짜,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분
77,크레센도,헤더 윌크,NaN,오드,오드,20231220.0,장편,미국,81.0,3653000.0,405.0,3416000.0,370.0,다큐멘터리,전체관람가,독립/예술영화
6644,크레센도,드로르 자하비,NaN,(주)티캐스트,(주)티캐스트,2021-06-,장편,독일,57.0,NaN,13.0,0.0,0.0,드라마,12세이상관람가,독립/예술영화

,영화제목,감독,제작사,수입사,유통사,개봉날짜,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분
77,크레센도,헤더 윌크,NaN,오드,오드,20231220.0,장편,미국,81.0,3653000.0,405.0,3416000.0,370.0,다큐멘터리,전체관람가,독립/예술영화
250,크레센도,헤더 윌크,NaN,오드,오드,20231220.0,장편,미국,81.0,21937500.0,2311.0,17517000.0,1804.0,다큐멘터리,전체관람가,독립/예술영화
420,크레센도,헤더 윌크,NaN,오드,오드,20231220.0,장편,미국,81.0,265429900.0,27565.0,132339200.0,13323.0,다큐멘터리,전체관람가,독립/예술영화
617,크레센도,헤더 윌크,NaN,오드,오드,20231220.0,장편,미국,81.0,395095300.0,36911.0,185698000.0,17242.0,다큐멘터리,전체관람가,독립/예술영화
6644,크레센도,드로르 자하비,NaN,(주)티캐스트,(주)티캐스트,2021-06-,장편,독일,57.0,NaN,13.0,0.0,0.0,드라마,12세이상관람가,독립/예술영화
6826,크레센도,드로르 자하비,NaN,(주)티캐스트,(주)티캐스트,2021-06-,장편,독일,57.0,NaN,85.0,NaN,36.0,드라마,12세이상관람가,독립/예술영화
7002,크레센도,드로르 자하비,NaN,(주)티캐스트,(주)티캐스트,2021-06-,장편,독일,57.0,NaN,253.0,NaN,251.0,드라마,12세이상관람가,독립/예술영화
7187,크레센도,드로르 자하비,NaN,(주)티캐스트,(주)티캐스트,2021-06-,장편,독일,57.0,NaN,NaN,NaN,NaN,드라마,12세이상관람가,독립/예술영화
7499,크레센도,드로르 자하비,NaN,(주)티캐스트,(주)티캐스트,20210624.0,장편,독일,57.0,NaN,NaN,NaN,NaN,드라마,12세이상관람가,독립/예술영화

In [602]:
# 오류 코드 바로 잡기
df.loc[4679, ["관람객", "서울관람객수"]] = 187, 177 # 벨파스트
df.loc[1306, ["관람객", "서울매출금액", "서울관람객수"]] = 1221, None, 330 # 말이야 바른 말이지
df.loc[7512, ["매출금액", "관람객", "서울매출금액", "서울관람객수"]] = 653801130, 75350, 112841710, 13207 # 극장판 콩순이: 장난감나라 대모험
df.loc[7763, ["관람객", "서울관람객수"]] = 354, 326 # 별의 목소리 X 초속5센티미터
df.loc[7764, ["관람객"]] = 334 # 컴 애즈 유 아
df.loc[4361, ["관람객", "서울관람객수"]] = 430, 324 # 리골레토
df.loc[3698, ["관람객", "서울관람객수"]] = 231, 199 # 블레이즈
df.loc[7704, cols] = 738027620, 80297.0 , 435500070.0, 47553.0 # 노매드랜드
df.loc[4932, ["관람객", "서울관람객수"]] = 418, 400 # 리코리쉬 피자
df.loc[8316, ["관람객", "서울매출금액", "서울관람객수"]] = 382, 300400.0 , 41 # 센코롤 커넥트
df.loc[1083, ["관람객", "서울관람객수"]] = 399, 183 # 킹 오브 뉴욕
df.loc[4956, ["관람객", "서울관람객수"]] = 1029, 933 # 레드 로켓
df.loc[3001, cols] = None, 140, None, 99 # 어웨이크
df.loc[3844, cols] = None, None, None, 71 # 어웨이크
df.loc[77, cols] = 686115700.0, 67192.0, 338970200.0, 32739.0 # 크레센도
df.loc[6644, cols] = None, 351, None, 287 # 크레센도
df.loc[8346, cols] = 33720500.0, 3883.0 , 19220950.0 , 2131 # 퍼스트 러브
df.loc[6643, cols] = None, 316, None, 1643 # 언더그라운드
df.loc[1285, cols] = None, 629, None, 440 # 마인드 유니버스
df.loc[6164, cols] = None, 333, None, 220 # 앰뷸런스
df.loc[7919, cols] = 220048440.0, 24571.0, 83205240.0, 9301.0 # 조제, 호랑이 그리고 물고기들
df.loc[3230, cols] = None, 100, None, 77 # 아르키메데스의 대전

In [603]:
df = df.drop([5313, 1043 ,2116, 7052, 7629, 7643, 2081, 6339, 5331,
              6748, 6334, 1307, 5357, 7214, 1095, 7554, 3447]) # 영화구분 혹은 영화형태만 중복인 데이터 삭제

In [604]:
del duplicated_movie
gc.collect();

In [605]:
print(df.shape)
resumtable(df) # 14개는 동명 영화

(7064, 16)

,피처,dtypes,결측치 갯수,고윳값 갯수,첫번째 값,두번째 값,세번째 값
0,영화제목,object,0,7050,파묘,듄: 파트2,댓글부대
1,감독,object,1158,2452,장재현,드니 빌뇌브,안국진
2,제작사,object,4067,763,"(주)쇼박스,(주)엠씨엠씨",NaN,"(주)영화적순간,주식회사 디믹스스튜디오"
3,수입사,object,4933,222,NaN,워너브러더스 코리아(주),NaN
4,유통사,object,1,541,(주)쇼박스,워너브러더스 코리아(주),(주)에이스메이커무비웍스
5,개봉날짜,object,1,843,20240222.0,20240228.0,20240327.0
6,영화형태,object,0,4,장편,장편,장편
7,국적,object,0,56,한국,미국,한국
8,총스크린수,float64,98,595,2355.0,1544.0,1228.0
9,매출금액,float64,3944,1315,105793676208.0,21940993462.0,5042399113.0
10,관람객,float64,268,1613,10957317.0,1886010.0,541058.0
11,서울매출금액,float64,1264,1207,24815149465.0,8730581144.0,1309676360.0
12,서울관람객수,float64,173,1464,2507635.0,687149.0,134016.0
13,장르,object,31,21,미스터리,액션,범죄
14,등급,object,0,7,15세이상관람가,12세이상관람가,15세이상관람가
15,영화구분,object,0,2,일반영화,일반영화,일반영화

## 개봉날짜 전처리

### 개봉날짜 결측치

In [606]:
df[df["개봉날짜"].isna()]

,영화제목,감독,제작사,수입사,유통사,개봉날짜,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분
1515,로보카폴리 안전교실 소방편,정광수,(주)로이비쥬얼,NaN,(주)로이비쥬얼,NaN,단편,한국,1.0,NaN,35.0,0.0,0.0,애니메이션,전체관람가,일반영화

In [607]:
df.loc[1515, "개봉날짜"] = 20230810
resumtable(df)

,피처,dtypes,결측치 갯수,고윳값 갯수,첫번째 값,두번째 값,세번째 값
0,영화제목,object,0,7050,파묘,듄: 파트2,댓글부대
1,감독,object,1158,2452,장재현,드니 빌뇌브,안국진
2,제작사,object,4067,763,"(주)쇼박스,(주)엠씨엠씨",NaN,"(주)영화적순간,주식회사 디믹스스튜디오"
3,수입사,object,4933,222,NaN,워너브러더스 코리아(주),NaN
4,유통사,object,1,541,(주)쇼박스,워너브러더스 코리아(주),(주)에이스메이커무비웍스
5,개봉날짜,object,0,843,20240222.0,20240228.0,20240327.0
6,영화형태,object,0,4,장편,장편,장편
7,국적,object,0,56,한국,미국,한국
8,총스크린수,float64,98,595,2355.0,1544.0,1228.0
9,매출금액,float64,3944,1315,105793676208.0,21940993462.0,5042399113.0
10,관람객,float64,268,1613,10957317.0,1886010.0,541058.0
11,서울매출금액,float64,1264,1207,24815149465.0,8730581144.0,1309676360.0
12,서울관람객수,float64,173,1464,2507635.0,687149.0,134016.0
13,장르,object,31,21,미스터리,액션,범죄
14,등급,object,0,7,15세이상관람가,12세이상관람가,15세이상관람가
15,영화구분,object,0,2,일반영화,일반영화,일반영화

In [608]:
# xxxx-xx- 이런식의 개봉날짜 형식 변환 필요
df[df["개봉날짜"].str.contains("-", na=False)]["개봉날짜"].unique() # 20221124 < 이런식으로 날짜나온 것들이 많아서 형식통일이후 데이트타임 변경 예정

array(['2022-10-', '2022-09-', '2022-11-', '2022-07-', '2022-08-',
       '2022-04-', '2022-06-', '2022-05-', '2021-12-', '2022-02-',
       '2022-01-', '2022-03-', '2021-10-', '2021-11-', '2021-07-',
       '2021-08-', '2021-09-', '2021-05-', '2021-06-', '2021-01-',
       '2021-03-', '2020-10-', '2021-04-'], dtype=object)

In [609]:
df.loc[df["개봉날짜"].str.contains("-", na=False), "개봉날짜"] = (
    df.loc[df["개봉날짜"].str.contains("-", na=False), "개봉날짜"] + "01") # 개봉"일" 자체는 안 중요하니 임시로 "01" 이란 날짜 생성 후에 삭제 예정

df[df["개봉날짜"].str.contains("-", na=False)]["개봉날짜"].unique()

array(['2022-10-01', '2022-09-01', '2022-11-01', '2022-07-01',
       '2022-08-01', '2022-04-01', '2022-06-01', '2022-05-01',
       '2021-12-01', '2022-02-01', '2022-01-01', '2022-03-01',
       '2021-10-01', '2021-11-01', '2021-07-01', '2021-08-01',
       '2021-09-01', '2021-05-01', '2021-06-01', '2021-01-01',
       '2021-03-01', '2020-10-01', '2021-04-01'], dtype=object)

In [610]:
df.loc[df["개봉날짜"].str.contains("-", na=False), "개봉날짜"] = (
    df.loc[df["개봉날짜"].str.contains("-", na=False), "개봉날짜"]
    .str.replace("-", "")
) # 개봉날짜에서 "-"기호 없애기

df[df["개봉날짜"].str.contains("-", na=False)]["개봉날짜"].unique()

array([], dtype=object)

In [611]:
df["개봉날짜"]

0        20240222.0
1        20240228.0
2        20240327.0
3        20240131.0
4        20240327.0
            ...
10867      20201113
10868      20200807
10869      20201116
10870      20200328
10871      20200925
Name: 개봉날짜, Length: 7064, dtype: object

In [612]:
df["개봉날짜"] = df["개봉날짜"].astype("int64") # 개봉날짜 인트로 바꿔서 소숫점 삭제
df["개봉날짜"]

0        20240222
1        20240228
2        20240327
3        20240131
4        20240327
           ...
10867    20201113
10868    20200807
10869    20201116
10870    20200328
10871    20200925
Name: 개봉날짜, Length: 7064, dtype: int64

In [613]:
df["개봉날짜"] = df["개봉날짜"].astype("str") # 다시 문자열로 변환
df["개봉날짜"] = pd.to_datetime(df["개봉날짜"]) # datetime으로 변환
df["개봉날짜"]

0       2024-02-22
1       2024-02-28
2       2024-03-27
3       2024-01-31
4       2024-03-27
           ...
10867   2020-11-13
10868   2020-08-07
10869   2020-11-16
10870   2020-03-28
10871   2020-09-25
Name: 개봉날짜, Length: 7064, dtype: datetime64[ns]

### 개봉연도, 개봉월 피쳐 생성

In [614]:
df["개봉연도"] = df["개봉날짜"].dt.year
df["개봉월"] = df["개봉날짜"].dt.month

df

,영화제목,감독,제작사,수입사,유통사,개봉날짜,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분,개봉연도,개봉월
0,파묘,장재현,"(주)쇼박스,(주)엠씨엠씨",NaN,(주)쇼박스,2024-02-22,장편,한국,2355.0,1.057937e+11,10957317.0,2.481515e+10,2507635.0,미스터리,15세이상관람가,일반영화,2024,2
1,듄: 파트2,드니 빌뇌브,NaN,워너브러더스 코리아(주),워너브러더스 코리아(주),2024-02-28,장편,미국,1544.0,2.194099e+10,1886010.0,8.730581e+09,687149.0,액션,12세이상관람가,일반영화,2024,2
2,댓글부대,안국진,"(주)영화적순간,주식회사 디믹스스튜디오",NaN,(주)에이스메이커무비웍스,2024-03-27,장편,한국,1228.0,5.042399e+09,541058.0,1.309676e+09,134016.0,범죄,15세이상관람가,일반영화,2024,3
3,웡카,폴 킹,NaN,워너브러더스 코리아(주),워너브러더스 코리아(주),2024-01-31,장편,미국,1753.0,3.390668e+10,3526213.0,9.818367e+09,980128.0,판타지,전체관람가,일반영화,2024,1
4,고질라 X 콩: 뉴 엠파이어,아담 윈가드,NaN,워너브러더스 코리아(주),워너브러더스 코리아(주),2024-03-27,장편,미국,996.0,3.220813e+09,320982.0,7.506203e+08,69172.0,액션,12세이상관람가,일반영화,2024,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10867,D컵여자친구,이정석,스마일컨텐츠,NaN,스마일컨텐츠,2020-11-13,장편,한국,1.0,5.000000e+03,1.0,0.000000e+00,0.0,멜로/로맨스,청소년관람불가,일반영화,2020,11
10868,F컵 거유의 육덕녀,버드맨 텟페이,NaN,(주)영진크리에이티브,(주)영진크리에이티브,2020-08-07,장편,일본,1.0,6.000000e+03,1.0,0.000000e+00,0.0,멜로/로맨스,청소년관람불가,일반영화,2020,8
10869,F컵 거유의 육덕녀 무삭제판,버드맨 텟페이,NaN,NaN,(주)영진크리에이티브,2020-11-16,장편,일본,1.0,6.000000e+03,1.0,0.000000e+00,0.0,멜로/로맨스,청소년관람불가,일반영화,2020,11
10870,G컵 베이글의 격렬한 플레이,NaN,NaN,(주)빅콘미디어,(주)빅콘미디어,2020-03-28,장편,일본,1.0,6.000000e+03,1.0,0.000000e+00,0.0,성인물(에로),청소년관람불가,일반영화,2020,3
10871,G컵 베이글의 능숙한 몸놀림,아라시야마 미치루,NaN,(주)빅콘미디어,(주)빅콘미디어,2020-09-25,장편,일본,1.0,6.000000e+03,1.0,0.000000e+00,0.0,성인물(에로),청소년관람불가,일반영화,2020,9

### 원본데이터 "개봉날짜" 피처 삭제

In [615]:
df = df.drop(columns="개봉날짜")
df

,영화제목,감독,제작사,수입사,유통사,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분,개봉연도,개봉월
0,파묘,장재현,"(주)쇼박스,(주)엠씨엠씨",NaN,(주)쇼박스,장편,한국,2355.0,1.057937e+11,10957317.0,2.481515e+10,2507635.0,미스터리,15세이상관람가,일반영화,2024,2
1,듄: 파트2,드니 빌뇌브,NaN,워너브러더스 코리아(주),워너브러더스 코리아(주),장편,미국,1544.0,2.194099e+10,1886010.0,8.730581e+09,687149.0,액션,12세이상관람가,일반영화,2024,2
2,댓글부대,안국진,"(주)영화적순간,주식회사 디믹스스튜디오",NaN,(주)에이스메이커무비웍스,장편,한국,1228.0,5.042399e+09,541058.0,1.309676e+09,134016.0,범죄,15세이상관람가,일반영화,2024,3
3,웡카,폴 킹,NaN,워너브러더스 코리아(주),워너브러더스 코리아(주),장편,미국,1753.0,3.390668e+10,3526213.0,9.818367e+09,980128.0,판타지,전체관람가,일반영화,2024,1
4,고질라 X 콩: 뉴 엠파이어,아담 윈가드,NaN,워너브러더스 코리아(주),워너브러더스 코리아(주),장편,미국,996.0,3.220813e+09,320982.0,7.506203e+08,69172.0,액션,12세이상관람가,일반영화,2024,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10867,D컵여자친구,이정석,스마일컨텐츠,NaN,스마일컨텐츠,장편,한국,1.0,5.000000e+03,1.0,0.000000e+00,0.0,멜로/로맨스,청소년관람불가,일반영화,2020,11
10868,F컵 거유의 육덕녀,버드맨 텟페이,NaN,(주)영진크리에이티브,(주)영진크리에이티브,장편,일본,1.0,6.000000e+03,1.0,0.000000e+00,0.0,멜로/로맨스,청소년관람불가,일반영화,2020,8
10869,F컵 거유의 육덕녀 무삭제판,버드맨 텟페이,NaN,NaN,(주)영진크리에이티브,장편,일본,1.0,6.000000e+03,1.0,0.000000e+00,0.0,멜로/로맨스,청소년관람불가,일반영화,2020,11
10870,G컵 베이글의 격렬한 플레이,NaN,NaN,(주)빅콘미디어,(주)빅콘미디어,장편,일본,1.0,6.000000e+03,1.0,0.000000e+00,0.0,성인물(에로),청소년관람불가,일반영화,2020,3
10871,G컵 베이글의 능숙한 몸놀림,아라시야마 미치루,NaN,(주)빅콘미디어,(주)빅콘미디어,장편,일본,1.0,6.000000e+03,1.0,0.000000e+00,0.0,성인물(에로),청소년관람불가,일반영화,2020,9

In [616]:
resumtable(df)

,피처,dtypes,결측치 갯수,고윳값 갯수,첫번째 값,두번째 값,세번째 값
0,영화제목,object,0,7050,파묘,듄: 파트2,댓글부대
1,감독,object,1158,2452,장재현,드니 빌뇌브,안국진
2,제작사,object,4067,763,"(주)쇼박스,(주)엠씨엠씨",NaN,"(주)영화적순간,주식회사 디믹스스튜디오"
3,수입사,object,4933,222,NaN,워너브러더스 코리아(주),NaN
4,유통사,object,1,541,(주)쇼박스,워너브러더스 코리아(주),(주)에이스메이커무비웍스
5,영화형태,object,0,4,장편,장편,장편
6,국적,object,0,56,한국,미국,한국
7,총스크린수,float64,98,595,2355.0,1544.0,1228.0
8,매출금액,float64,3944,1315,105793676208.0,21940993462.0,5042399113.0
9,관람객,float64,268,1613,10957317.0,1886010.0,541058.0
10,서울매출금액,float64,1264,1207,24815149465.0,8730581144.0,1309676360.0
11,서울관람객수,float64,173,1464,2507635.0,687149.0,134016.0
12,장르,object,31,21,미스터리,액션,범죄
13,등급,object,0,7,15세이상관람가,12세이상관람가,15세이상관람가
14,영화구분,object,0,2,일반영화,일반영화,일반영화
15,개봉연도,int32,0,7,2024,2024,2024
16,개봉월,int32,0,12,2,2,3

## 결측치

### 유통사

In [617]:
df[df["유통사"].isna()]

,영화제목,감독,제작사,수입사,유통사,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분,개봉연도,개봉월
9644,빚투: 부부교환 무삭제,정미나,NaN,NaN,NaN,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,12

In [618]:
df[df["감독"] == "정미나"] # 정미나 감독 유통사가 하나밖에 없으므로 결측치 채움

,영화제목,감독,제작사,수입사,유통사,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분,개봉연도,개봉월
8006,니 남편 니 아내,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2021,4
8548,공인섹스중개사,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2021,2
8549,귀신한테 싼다,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2021,2
8555,맛있는 섹스 그리고 요정,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2021,2
9482,그녀의 모유는 백신,정미나,(주)담화,NaN,(주)담화,장편,한국,20.0,937000.0,170.0,663000.0,125.0,성인물(에로),청소년관람불가,일반영화,2020,8
9510,주부남편의 발기찬 바깥생활,정미나,(주)담화,NaN,(주)담화,장편,한국,20.0,935000.0,169.0,663000.0,125.0,성인물(에로),청소년관람불가,일반영화,2020,7
9630,리얼섹스돌 : 사용설명서 무삭제,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,9
9632,맛있는 너가 합격,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,9
9636,무엇이든 도와드립니다,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,10
9643,빚투: 부부교환,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,10
9644,빚투: 부부교환 무삭제,정미나,NaN,NaN,NaN,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,12
9648,세자매 은밀한 섹파,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,7
9660,섹스인듯 촬영인듯 섹스하는 너,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,9
9671,아이돌 섹스: LA 교포녀,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,6
9672,아이돌 섹스: LA 교포녀 무삭제,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,9
9673,애인의 가슴 큰 친구,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,12
9677,여배우들: 섹스 오디션,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,7
9678,여배우들: 섹스 오디션 무삭제,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,9
9687,오빠는 음식은 가려도 여자는 안가려,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,5
9688,오빠는 음식은 가려도 여자는 안가려 무삭제,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,9
9705,주부남편의 발기찬 바깥생활 무삭제,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,10
9714,팽말숙 : 실전주의,정미나,(주)담화,NaN,(주)담화,장편,한국,1.0,300000.0,60.0,300000.0,60.0,성인물(에로),청소년관람불가,일반영화,2020,11

In [619]:
df.loc[9644, "유통사"] = "(주)담화"
resumtable(df)

,피처,dtypes,결측치 갯수,고윳값 갯수,첫번째 값,두번째 값,세번째 값
0,영화제목,object,0,7050,파묘,듄: 파트2,댓글부대
1,감독,object,1158,2452,장재현,드니 빌뇌브,안국진
2,제작사,object,4067,763,"(주)쇼박스,(주)엠씨엠씨",NaN,"(주)영화적순간,주식회사 디믹스스튜디오"
3,수입사,object,4933,222,NaN,워너브러더스 코리아(주),NaN
4,유통사,object,0,541,(주)쇼박스,워너브러더스 코리아(주),(주)에이스메이커무비웍스
5,영화형태,object,0,4,장편,장편,장편
6,국적,object,0,56,한국,미국,한국
7,총스크린수,float64,98,595,2355.0,1544.0,1228.0
8,매출금액,float64,3944,1315,105793676208.0,21940993462.0,5042399113.0
9,관람객,float64,268,1613,10957317.0,1886010.0,541058.0
10,서울매출금액,float64,1264,1207,24815149465.0,8730581144.0,1309676360.0
11,서울관람객수,float64,173,1464,2507635.0,687149.0,134016.0
12,장르,object,31,21,미스터리,액션,범죄
13,등급,object,0,7,15세이상관람가,12세이상관람가,15세이상관람가
14,영화구분,object,0,2,일반영화,일반영화,일반영화
15,개봉연도,int32,0,7,2024,2024,2024
16,개봉월,int32,0,12,2,2,3

### 장르

In [620]:
df[df["장르"].isna()]

,영화제목,감독,제작사,수입사,유통사,영화형태,국적,총스크린수,매출금액,관람객,서울매출금액,서울관람객수,장르,등급,영화구분,개봉연도,개봉월
513,관능 육체 부녀회장의 동정교육,NaN,주식회사 피에스앤제이,NaN,주식회사 피에스앤제이,장편,한국,1.0,100000.0,20.0,0.0,0.0,NaN,청소년관람불가,일반영화,2024,1
676,사형에 이르는 병,시라이시 카즈야,NaN,(주)태양미디어그룹,"(주)태양미디어그룹,와이드 릴리즈(주)",장편,일본,28.0,19355478.0,2040.0,15234789.0,1560.0,NaN,청소년관람불가,독립/예술영화,2023,11
865,시수,얄마리 헬렌더,NaN,(주)도키엔터테인먼트,(주)이놀미디어,장편,기타,175.0,9629510.0,1428.0,2700410.0,319.0,NaN,청소년관람불가,독립/예술영화,2023,10
889,걸스 인 원더랜드 : 벤타엑스 브이알 뮤직시네마 02,NaN,NaN,NaN,벤타브이알,장편,한국,1.0,18350000.0,734.0,15300000.0,612.0,NaN,전체관람가,일반영화,2023,11
1054,스크래퍼,NaN,NaN,그린나래미디어(주),"그린나래미디어(주),(주)스튜디오 산타클로스엔터테인먼트",장편,영국,45.0,NaN,NaN,NaN,NaN,NaN,12세이상관람가,독립/예술영화,2023,9
1067,팟 제너레이션,소피 바르트,NaN,"주식회사 왓챠,(재)전주국제영화제조직위원회",주식회사 왓챠,장편,기타,25.0,NaN,NaN,NaN,884.0,NaN,12세이상관람가,독립/예술영화,2023,10
1116,이누부!,시노하라 테츠오,NaN,(주)미디어캐슬,(주)미디어캐슬,장편,일본,4.0,NaN,52.0,NaN,4.0,NaN,전체관람가,독립/예술영화,2023,10
1334,더 버닝 씨,NaN,NaN,(주)엣나인필름,(주)엣나인필름,장편,노르웨이,36.0,NaN,978.0,NaN,594.0,NaN,12세이상관람가,독립/예술영화,2023,8
1346,검은 상복의 모녀,김태훈,주식회사 피에스앤제이,NaN,주식회사 피에스앤제이,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,9
1347,결혼을 반대한 형이 아내를 건드렸다,핑마,와이제이스토리,NaN,와이제이스토리,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,9
1349,교환부부의 세계3 ： 그들만의 은밀한 테크닉,NaN,주식회사 루믹스미디어,NaN,주식회사 루믹스미디어,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,9
1351,그래픽 디자이어,NaN,NaN,NaN,(주)콘텐트마인,장편,영국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,9
1352,남자전용 미용실,NaN,주식회사 루믹스미디어,NaN,주식회사 루믹스미디어,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,9
1353,남친이 군대 간 사이,NaN,주식회사 루믹스미디어,NaN,주식회사 루믹스미디어,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,9
1373,사먹는 세자매,NaN,주식회사 루믹스미디어,NaN,주식회사 루믹스미디어,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,9
1378,새엄마 아빠에게는 비밀로 해요,NaN,NaN,NaN,(주)영진크리에이티브,장편,일본,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,9
1381,술집에서 몰래 하는 사이,핑마,와이제이스토리,NaN,와이제이스토리,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,9
1384,여사장 : 월급대신 떡,NaN,(주)영화사가을,NaN,(주)영화사가을,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,9
1405,AS기사 유혹하는 여주인,핑마,와이제이스토리,NaN,와이제이스토리,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,9
1512,더 도어 : 다섯 개의 문,"블라디미르 마슬로프,미하일 모스코프,비탈리 두드카",NaN,NaN,주식회사 원더스튜디오,장편,러시아,5.0,NaN,40.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,8
1543,그녀의 PS파트너,NaN,주식회사 루믹스미디어,NaN,주식회사 루믹스미디어,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,8
1572,어린 처제2,NaN,영화사 레드카펫,NaN,주식회사 루믹스미디어,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,8
1573,여대생 가사도우미,NaN,NaN,NaN,주식회사 루믹스미디어,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,8
1581,우리동네 미용실 ： 2대1서비스,한마음,주식회사 루믹스미디어,NaN,주식회사 루믹스미디어,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,8
1596,젖 큰 가정교사와 이대일 2,조현규,주식회사 루믹스미디어,NaN,주식회사 루믹스미디어,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,8
1614,mz 자매의 목적,함성한,P&미디어,NaN,P&미디어,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,8
1756,골프레슨 특별한 기술,오지인,주식회사 루믹스미디어,NaN,주식회사 루믹스미디어,장편,한국,1.0,NaN,1.0,0.0,0.0,NaN,청소년관람불가,일반영화,2023,7
6623,그녀의 가족은 잘못이 없어,김헌,이상우필름,NaN,이상우필름,장편,한국,2.0,NaN,22.0,0.0,0.0,NaN,15세이상관람가,독립/예술영화,2021,10
9574,여직원 사용 설명서,마의성,노바엔터테인먼트,NaN,노바엔터테인먼트,장편,한국,20.0,400000.0,79.0,302000.0,61.0,NaN,청소년관람불가,일반영화,2020,3
9575,청불학원2,김석만,노바엔터테인먼트,NaN,노바엔터테인먼트,장편,한국,20.0,400000.0,79.0,302000.0,61.0,NaN,청소년관람불가,일반영화,2020,3
9576,형수의 성교육,김석만,노바엔터테인먼트,NaN,노바엔터테인먼트,장편,한국,20.0,400000.0,79.0,302000.0,61.0,NaN,청소년관람불가,일반영화,2020,3

In [621]:
df.loc[676, "장르"] = "미스터리" # 사형에 이르는 병
df.loc[865, "장르"] = "액션" # 시수
df.loc[889, "장르"] = "공연" # 걸스 인 원더랜드 : 벤타엑스 브이알 뮤직시네마 02
df.loc[1054, "장르"] = "코미디" # 스크래퍼
df.loc[1067, "장르"] = "SF" # 팟 제너레이션
df.loc[1116, "장르"] = "가족" # 이누부!
df.loc[1334, "장르"] = "액션" # 더 버닝 씨
df.loc[1351, "장르"] = "멜로/로맨스" # 그래픽 디자이어
df.loc[1512, "장르"] = "스릴러" # 더 도어 : 다섯 개의 문
df.loc[6623, "장르"] = "드라마" # 그녀의 가족은 잘못이 없어
df["장르"] = df["장르"].fillna("성인물(에로)") # 나머진 전부 에로물

resumtable(df)

,피처,dtypes,결측치 갯수,고윳값 갯수,첫번째 값,두번째 값,세번째 값
0,영화제목,object,0,7050,파묘,듄: 파트2,댓글부대
1,감독,object,1158,2452,장재현,드니 빌뇌브,안국진
2,제작사,object,4067,763,"(주)쇼박스,(주)엠씨엠씨",NaN,"(주)영화적순간,주식회사 디믹스스튜디오"
3,수입사,object,4933,222,NaN,워너브러더스 코리아(주),NaN
4,유통사,object,0,541,(주)쇼박스,워너브러더스 코리아(주),(주)에이스메이커무비웍스
5,영화형태,object,0,4,장편,장편,장편
6,국적,object,0,56,한국,미국,한국
7,총스크린수,float64,98,595,2355.0,1544.0,1228.0
8,매출금액,float64,3944,1315,105793676208.0,21940993462.0,5042399113.0
9,관람객,float64,268,1613,10957317.0,1886010.0,541058.0
10,서울매출금액,float64,1264,1207,24815149465.0,8730581144.0,1309676360.0
11,서울관람객수,float64,173,1464,2507635.0,687149.0,134016.0
12,장르,object,0,21,미스터리,액션,범죄
13,등급,object,0,7,15세이상관람가,12세이상관람가,15세이상관람가
14,영화구분,object,0,2,일반영화,일반영화,일반영화
15,개봉연도,int32,0,7,2024,2024,2024
16,개봉월,int32,0,12,2,2,3

### 중간저장 - feature_engineering용

In [622]:
# df.to_csv("movie_for_feature_engineering.csv", index=False) # feature_engineering 용으로 사용할 데이터

### 감독, 제작사, 수입사 
- 전부 결측치가 많아서 etc로 대체

In [623]:
na_cols = ["감독", "제작사", "수입사"]
df[na_cols] = df[na_cols].fillna("etc")

resumtable(df)

,피처,dtypes,결측치 갯수,고윳값 갯수,첫번째 값,두번째 값,세번째 값
0,영화제목,object,0,7050,파묘,듄: 파트2,댓글부대
1,감독,object,0,2453,장재현,드니 빌뇌브,안국진
2,제작사,object,0,764,"(주)쇼박스,(주)엠씨엠씨",etc,"(주)영화적순간,주식회사 디믹스스튜디오"
3,수입사,object,0,223,etc,워너브러더스 코리아(주),etc
4,유통사,object,0,541,(주)쇼박스,워너브러더스 코리아(주),(주)에이스메이커무비웍스
5,영화형태,object,0,4,장편,장편,장편
6,국적,object,0,56,한국,미국,한국
7,총스크린수,float64,98,595,2355.0,1544.0,1228.0
8,매출금액,float64,3944,1315,105793676208.0,21940993462.0,5042399113.0
9,관람객,float64,268,1613,10957317.0,1886010.0,541058.0
10,서울매출금액,float64,1264,1207,24815149465.0,8730581144.0,1309676360.0
11,서울관람객수,float64,173,1464,2507635.0,687149.0,134016.0
12,장르,object,0,21,미스터리,액션,범죄
13,등급,object,0,7,15세이상관람가,12세이상관람가,15세이상관람가
14,영화구분,object,0,2,일반영화,일반영화,일반영화
15,개봉연도,int32,0,7,2024,2024,2024
16,개봉월,int32,0,12,2,2,3

### 중간저장 - EDA용

In [624]:
# df.to_csv("movie_for_EDA.csv", index=False) # EDA용 데이터

### 총스크린수, 매출금액, 관람객, 서울매출금액, 서울관람객수
- baseline용으로 0으로 채움
- feature_engineering 단계에서는 통계를 내어서 채울예정
    - 결측치 전부 해결 데이터 분할하는 방법
    - train, test 분할 이후 결측치 채우는 방법

In [625]:
df = df.fillna(0) # 나머지 결측치 0으로 채움
resumtable(df)

,피처,dtypes,결측치 갯수,고윳값 갯수,첫번째 값,두번째 값,세번째 값
0,영화제목,object,0,7050,파묘,듄: 파트2,댓글부대
1,감독,object,0,2453,장재현,드니 빌뇌브,안국진
2,제작사,object,0,764,"(주)쇼박스,(주)엠씨엠씨",etc,"(주)영화적순간,주식회사 디믹스스튜디오"
3,수입사,object,0,223,etc,워너브러더스 코리아(주),etc
4,유통사,object,0,541,(주)쇼박스,워너브러더스 코리아(주),(주)에이스메이커무비웍스
5,영화형태,object,0,4,장편,장편,장편
6,국적,object,0,56,한국,미국,한국
7,총스크린수,float64,0,595,2355.0,1544.0,1228.0
8,매출금액,float64,0,1316,105793676208.0,21940993462.0,5042399113.0
9,관람객,float64,0,1614,10957317.0,1886010.0,541058.0
10,서울매출금액,float64,0,1207,24815149465.0,8730581144.0,1309676360.0
11,서울관람객수,float64,0,1464,2507635.0,687149.0,134016.0
12,장르,object,0,21,미스터리,액션,범죄
13,등급,object,0,7,15세이상관람가,12세이상관람가,15세이상관람가
14,영화구분,object,0,2,일반영화,일반영화,일반영화
15,개봉연도,int32,0,7,2024,2024,2024
16,개봉월,int32,0,12,2,2,3

### 중간저장 - baseline용

In [626]:
# df.to_csv("movie_for_baseline.csv", index=False) # basline 용으로 사용할 데이터

# 정리하기
- 데이터 분할시 최신데이터를 test로 하기 위해 가장 위쪽에 배치
- 한글 피처명 변경
- 필요 없는 피처 삭제
- 데이터 통일(중복 데이터 제거, 개봉날짜 형태 통일)
- baseline, EDA, feature_engineering에 필요한 데이터 각각 추출
- 결측치
    - 고정
        - 유통사, 장르(1개씩 밖에 없음)
    - 비고정
        - 감독, 제작사, 수입사(굉장히 많음)
            - etc로 채웠으나 다른거로 채울 여지 있음
            - baseline 코드 이후 제거할 수도 있음
        - 총스크린수, 매출금액, 관람객, 서울매출금액, 서울관람객수
            - baseline용으로 0
            - feature_engineering용으로 통계치 구해서 채울 예정